from alembic import op
import sqlalchemy as sa

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    op.create_table("airports", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("icao", sa.String(4), nullable=False, unique=True), sa.Column("iata", sa.String(3)), sa.Column("name", sa.String(255), nullable=False), sa.Column("location", sa.String(255)), sa.Column("elevation_ft", sa.Integer()), sa.Column("source_status", sa.String(32), nullable=False, server_default="UNKNOWN"))
    op.create_table("runways", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("airport_id", sa.Integer(), sa.ForeignKey("airports.id", ondelete="CASCADE"), nullable=False), sa.Column("designator", sa.String(8), nullable=False), sa.Column("length_m", sa.Float()), sa.Column("width_m", sa.Float()), sa.Column("surface", sa.String(64)), sa.Column("closed", sa.Boolean(), nullable=False, server_default=sa.false()), sa.Column("pavement_json", sa.JSON()), sa.Column("source_reference", sa.JSON()))
    op.create_table("taxiways", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("airport_id", sa.Integer(), sa.ForeignKey("airports.id", ondelete="CASCADE"), nullable=False), sa.Column("designator", sa.String(16), nullable=False), sa.Column("width_m", sa.Float()), sa.Column("surface", sa.String(64)), sa.Column("pavement_json", sa.JSON()), sa.Column("published_weight_limit_t", sa.Float()), sa.Column("restrictions", sa.JSON()))
    op.create_table("source_documents", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("source_code", sa.String(64), nullable=False), sa.Column("document_type", sa.String(64), nullable=False), sa.Column("airport_icao", sa.String(4)), sa.Column("revision", sa.String(128)), sa.Column("status", sa.String(32), nullable=False, server_default="DISCOVERED"), sa.Column("document_url", sa.Text()), sa.Column("content_hash", sa.String(128)), sa.Column("parser_version", sa.String(64)), sa.Column("raw_metadata", sa.JSON()), sa.Column("created_at", sa.DateTime(timezone=True)), sa.Column("updated_at", sa.DateTime(timezone=True)))
    op.create_table("field_provenance", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("document_id", sa.Integer(), sa.ForeignKey("source_documents.id", ondelete="CASCADE"), nullable=False), sa.Column("field_path", sa.String(255), nullable=False), sa.Column("raw_value", sa.Text()), sa.Column("normalized_value", sa.JSON()), sa.Column("value_status", sa.String(32), nullable=False), sa.Column("confidence", sa.Float()), sa.Column("source_reference", sa.JSON()), sa.Column("review_status", sa.String(32), nullable=False))
    op.create_table("aircraft_profiles", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("code", sa.String(16), nullable=False, unique=True), sa.Column("variant", sa.String(64), nullable=False), sa.Column("data_status", sa.String(64), nullable=False), sa.Column("profile_json", sa.JSON(), nullable=False))
    op.create_table("acn_points", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("aircraft_profile_id", sa.Integer(), sa.ForeignKey("aircraft_profiles.id", ondelete="CASCADE"), nullable=False), sa.Column("pavement_type", sa.String(1), nullable=False), sa.Column("subgrade", sa.String(1), nullable=False), sa.Column("mass_kg", sa.Float(), nullable=False), sa.Column("acn", sa.Float(), nullable=False), sa.Column("source_revision", sa.String(128), nullable=False), sa.Column("is_official", sa.Boolean(), nullable=False, server_default=sa.false()))
    op.create_table("metar_observations", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("station", sa.String(4), nullable=False), sa.Column("raw_metar", sa.Text(), nullable=False), sa.Column("observed_at", sa.DateTime(timezone=True)), sa.Column("temperature_c", sa.Float()), sa.Column("qnh_hpa", sa.Float()), sa.Column("payload", sa.JSON()), sa.Column("source", sa.String(32), nullable=False), sa.Column("retrieved_at", sa.DateTime(timezone=True)))
    op.create_table("notams", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("airport_icao", sa.String(4), nullable=False), sa.Column("number", sa.String(64)), sa.Column("raw_text", sa.Text(), nullable=False), sa.Column("status", sa.String(32), nullable=False), sa.Column("decoding_status", sa.String(32), nullable=False), sa.Column("category", sa.String(32), nullable=False), sa.Column("severity", sa.String(32), nullable=False), sa.Column("payload", sa.JSON()), sa.Column("retrieved_at", sa.DateTime(timezone=True)))
    op.create_table("assessments", sa.Column("id", sa.String(36), primary_key=True), sa.Column("airport_icao", sa.String(4), nullable=False), sa.Column("status", sa.String(64), nullable=False), sa.Column("created_by", sa.String(128), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True)), sa.Column("request_snapshot", sa.JSON(), nullable=False), sa.Column("result_snapshot", sa.JSON(), nullable=False))
    op.create_table("validation_results", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("assessment_id", sa.String(36), sa.ForeignKey("assessments.id", ondelete="CASCADE"), nullable=False), sa.Column("rule_code", sa.String(128), nullable=False), sa.Column("status", sa.String(32), nullable=False), sa.Column("severity", sa.String(32), nullable=False), sa.Column("message", sa.Text(), nullable=False), sa.Column("actual_value", sa.JSON()), sa.Column("required_value", sa.JSON()), sa.Column("source_reference", sa.JSON()))
    op.create_table("audit_events", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("actor", sa.String(128), nullable=False), sa.Column("action", sa.String(128), nullable=False), sa.Column("resource_type", sa.String(64), nullable=False), sa.Column("resource_id", sa.String(128)), sa.Column("payload", sa.JSON()), sa.Column("created_at", sa.DateTime(timezone=True)))

def downgrade():
    for name in ["audit_events", "validation_results", "assessments", "notams", "metar_observations", "acn_points", "aircraft_profiles", "field_provenance", "source_documents", "taxiways", "runways", "airports"]:
        op.drop_table(name)
